version: '3'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - celery
      - mongodb
  mongodb:
    image: mongo
    volumes:
      - ~/mongodb-data:/data/db
    ports:
      - "27017:27017"
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  celery:
    build: .
    command: celery -A rewaa_ingestion_api worker -l debug
    volumes:
      - .:/usr/src/app/
    depends_on:
      - redis
      - mongodb
